title: Digitally Mi
description: "Mostly disc golf with a little bit of everything else sprinkled in. ✨"
baseurl: "" # Leave this empty for root deployment
url: "https://meeeyuh.github.io" # Replace with your GitHub Pages URL

# Disable default theme (no Minima)
theme: null

# Collections (if needed in future)
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed